name: 'Bump Version in Version file'
inputs:
  version_file:  # id of input
    required: false
  version:
    required: false
    
outputs:
  bumped_version:
    description: "the version the is newly bumped to"
    value: ${{ steps.bump-version.outputs.new_version }}    
runs:
  using: "composite"
  steps:
    - name: run script to bump version file provided
      run: ${{ github.action_path }}/bump_version_file.sh ${{inputs.version_file}}
      shell: bash
      if ${{version_file}}
      
    - name: run script to bump version file provided
      run: ${{ github.action_path }}/bump_version.sh ${{inputs.version}}
      shell: bash
      if ${{version}}  
      
      
      
    - id: bump-version
      run: echo "::set-output name=new_version::$(cat ${{inputs.version_file}})"
      shell: bash
     
